### ISSUE TITLE
WinFormプロジェクトの作成＋ウィンドウ内の区画分け

### ISSUE THREAD

**Issue by MachineHunter** [MachineHunter/SafeExecute#19]
まず、VisualC++のWinFormプロジェクトを作成しする。
次にPanelを使って、以下のように三つの区画を作る。

![image](https://user-images.githubusercontent.com/56915604/189868263-20ecd862-2f25-41d6-8a96-a721d95e9bcc.png)

**Comment by kaichooo** [comment]
winform-guiブランチで
- WinFormディレクトリにWinFormプロジェクトを作成
- Panelを使って3つの区画を設置(名前は仮)
　- target_exe_selection_panel: 実行ファイルを選ぶためのパネル
　- selection_panel: 制限する挙動のチェックリストを書くためのパネル
　- output_panel: 標準出力やエラー出力を表示するためのパネル
　* パネルを見やすくするためにパネルの背景に色付けしている

**Comment by MachineHunter** [comment]
プロジェクト名変更の関係で他の人が開けない問題でてきたので、
もう一回最初から作成してもらう。
